create table transaction (id bigint generated by default as identity, buyer varchar(255), currency varchar(255), fees double, product varchar(255), quantity integer, seller varchar(255), total_amount double, trade_date timestamp, unit_price double, primary key (id))

